[controlplane]

controlplane node_type=controlplane primary=true

[slave]

node01 node_type=worker primary=false

[all:vars]

env=learning 

[controlplane:vars]

dns_server=1.9.0.5

[slave:vars]

dns_server=8.8.8.8
